const COLOR = {

    BG_GRAY_DARKER : "#BEC9D9",
    BG_GRAY : "#D2DDEC",
    BG_GRAY_LIGHT : "#E4EBF6",
    BG_GRAY_LIGHTER : "#EFF2F7",
    BG_GRAY_LIGHTEST : "#F9FAFC",

    PRIMARY : "#2C7BE5",
    TEXT_COLOR : "#1F2D3D",
    TEXT_COLOR_2: "#8492A6",
    BLUE_LIGHT: "#D0EFF6",

    DARK_BTN_SECONDARY: "#244166",

    SUCCESS: "#17CD6E",

    BLACK : "#000",
    WHITE : "#fff",
    GRAY_MAIN : "#F2F1EA",
    //

    BG_TITLE_SECTION_MAIN : "#F2F1EB",
    TEXT_COLOR_STATUS_PRO: "#9E513B",
    TEXT_COLOR_STATUS_PRO_HAS: "#79A746",
    TEXT_COLOR_MENU_CUSTOMS: "#191919",
    BG_GRAY_MENU: "#F2F1EA",
    BG_GRAY_POPUP: "#F2F1EA",
}

export default COLOR;
